services:
    liip_imagine_additional_filters_pixelate:
        class:  Neok\LiipImagineAdditionalFiltersBundle\Imagine\Filter\Loader\PixelateLoader
        arguments: ['gd']
        tags:
            - { name: liip_imagine.filter.loader, loader: pixelate_filter }
