services:
    liip_imagine_additional_filters_pixelate:
        class:  Kruczkowski\LiipImagineAdditionalFiltersBundle\Imagine\Filter\Loader\PixelateLoader
        tags:
            - { name: liip_imagine.filter.loader, loader: pixelate_filter }

    liip_imagine_additional_filters_blur:
        class:  Kruczkowski\LiipImagineAdditionalFiltersBundle\Imagine\Filter\Loader\BlurLoader
        tags:
            - { name: liip_imagine.filter.loader, loader: blur_filter }
